version: "3.8"

services:
  inzynierka_server:
    build: .
    ports:
      - "8000:8000" # FastAPI
      - "5678:5678" # debugpy
    depends_on:
      - izynierka_db
    volumes:
      - ./app:/code/app
    command: >
      sh -c "python -m debugpy --listen 0.0.0.0:5678 app/main.py"
    env_file:
      - ./.env

  izynierka_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
