version: "3.8"

services:
  inzynierka_server:
    build: .
    ports:
      - "8000:8000" # FastAPI
    depends_on:
      - izynierka_db
    volumes:
      - ./app:/code/app
    command: >
      sh -c "python app/main.py"
    env_file:
      - ./.env

  izynierka_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
