version: "3.8"

services:
  # Service for running tests
  web_test:
    build: .
    ports:
      - "8005:8005"
    depends_on:
      - db_test
    volumes:
      - ./app:/code/app
    command: >
      sh -c "pytest -v --tb=long -s --disable-warnings -k test_"
    env_file:
      - ./.env
    networks:
      - test_network
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:password@db_test:5432/test

  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    networks:
      - test_network

volumes:
  test_postgres_data:

networks:
  test_network:
    driver: bridge
